image: atlassian/default-image:3

pipelines:
    branches:
        development:
            - step:
                  script:
                      - echo "yarn install"
                      - echo "yarn androidReleaseAPK"
