# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    branches:
        development:
            - step:
                  max-time: 120
                  size: "1x"
                  script:
                      - echo yarn install
                      - echo yarn androidRelease-Dev
                  trigger: automatic
