# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: node:10.15.3

pipelines:
    branches:
        main: #name of your test branch
            - step:
                  image: node:10.15.3
                  caches:
                      - node
                      - gradle
                  script: # Modify the commands below to build your repository.
                      #env preperation
                      - yarn install
            - step:
                  image: mingc/android-build-box:latest
                  caches:
                      - node
                  script: # Modify the commands below to build your repository
                      #build
                      - cd ./android
                      - chmod +x gradlew
                      - ./gradlew assembleRelease
                      - ls -R
