const COMPANY = "COMPANY";
const INDIVIDU = "INDIVIDU";
const PERUSAHAAN = "PERUSAHAAN";
const DEBOUNCE_SEARCH = 500;

const DEFAULT_ESTIMATED_LIST_SIZE = 10;
const DEFAULT_ON_END_REACHED_THREHOLD = 0.5;

const COMMON_API_SERVER_DEV = "common.apis.oreo.brik.id";
const COMMON_API_SERVER_PROD = "common.apis.brik.id";

const COMMON_API_SERVER = COMMON_API_SERVER_DEV || COMMON_API_SERVER_PROD;

const INVENTORY_API_SERVER_DEV = "inventory.apis.oreo.brik.id";
const INVENTORY_API_SERVER_PROD = "inventory.apis.brik.id";

const INVENTORY_API_SERVER =
    INVENTORY_API_SERVER_DEV || INVENTORY_API_SERVER_PROD;

const PRODUCTIVITY_API_SERVER_DEV = "productivity.apis.oreo.brik.id";
const PRODUCTIVITY_API_SERVER_PROD = "productivity.apis.brik.id";

const PRODUCTIVITY_API_SERVER =
    PRODUCTIVITY_API_SERVER_DEV || PRODUCTIVITY_API_SERVER_PROD;

const ORDER_API_SERVER_DEV = "order.apis.oreo.brik.id";
const ORDER_API_SERVER_PROD = "order.apis.brik.id";

const ORDER_API_SERVER = ORDER_API_SERVER_DEV || ORDER_API_SERVER_PROD;

const FINANCE_API_SERVER_DEV = "finance.apis.oreo.brik.id";
const FINANCE_API_SERVER_PROD = "finance.apis.brik.id";

const FINANCE_API_SERVER = FINANCE_API_SERVER_DEV || FINANCE_API_SERVER_PROD;

export {
    COMPANY,
    INDIVIDU,
    PERUSAHAAN,
    DEBOUNCE_SEARCH,
    COMMON_API_SERVER_DEV,
    COMMON_API_SERVER_PROD,
    COMMON_API_SERVER,
    INVENTORY_API_SERVER_DEV,
    INVENTORY_API_SERVER_PROD,
    INVENTORY_API_SERVER,
    PRODUCTIVITY_API_SERVER_DEV,
    PRODUCTIVITY_API_SERVER_PROD,
    PRODUCTIVITY_API_SERVER,
    ORDER_API_SERVER_DEV,
    ORDER_API_SERVER_PROD,
    ORDER_API_SERVER,
    FINANCE_API_SERVER_DEV,
    FINANCE_API_SERVER_PROD,
    FINANCE_API_SERVER,
    DEFAULT_ESTIMATED_LIST_SIZE,
    DEFAULT_ON_END_REACHED_THREHOLD
};
