export enum ENTRY_TYPE {
  OPSMANAGER = 'OPSMANAGER',
  SALES = 'SALES',
  BATCHER = 'BATCHER',
  SECURITY = 'SECURITY',
  WB = 'WB',
  DISPATCH = 'DISPATCH',
  RETURN = 'RETURN',
  DRIVER = 'DRIVER',
  ADMIN = 'ADMIN'
}
